Tech/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from django.conf.urls.static import static
from django.conf import settings
from Tech import views as Tech_views

app_name = 'Tech'

urlpatterns = [
    path('', PeListView, name='list'),
    path('current_user/', current_user),
    path('users/', UserList.as_view()),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('add/', PeCreateView, name='add'),
    path('catask/<int:pk>', CaTaskView, name='catask1'),
    #path('catask/dep/<int:pk>', DepCreateView, name='dep'),
    path('delete/<int:pk>',PeDeleteView,name='delete'),
    path('catask/<int:pk>/file',fileRead,name='FR'),
    path('catask/<int:pk>/<int:id>/fd', filedown, name='FD'),
    path('catask/<int:pk>/<int:tnum>',TaskContentView,name='catask2'),
    path('catask/<int:pk>/<int:tnum>/mod',TaskMod,name='TaskMod'),
    path('catask/<int:pk>/<int:tnum>/user',TaskUserCreate,name='TaskUser'),
    path('catask/<int:pk>/<int:tnum>/team',TaskTeamCreate,name='TaskTeam'),
    path('catask/<int:pk>/<int:tnum>/<int:id>', ContentsUpdateView, name='coup'),
    path('catask/<int:pk>/<int:tnum>/com', comment, name='comment'),
    path('catask/<int:pk>/<int:tnum>/<int:id>/com', comment_reply, name='reply'),
    path('catask/<int:pk>/<int:tnum>/<int:id>/comdel', comment_delete, name='codel'),
    path('catask/<int:pk>/<int:tnum>/<int:id>/comupdate', comment_Update, name='comup')
    #path('catask/<int:pk>/<int:tnum>/<int:id>/file', fileupload, name='fileup')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TechCommunity/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_jwt.views import obtain_jwt_token
from Tech.views import show

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', show, name='show'),
    path('api-token-auth/',obtain_jwt_token),
    path('Tech/', include('Tech.urls')),
    path('admin/', admin.site.urls),
    path('accounts/',include('allauth.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
  </head>
  <body>
    {% block body %}

    <div>
        {% if user.is_authenticated %}
        <a href="{% url 'account_logout' %}">Sign Out</a>
        {% else %}
        <a href="{% url 'account_login' %}">Sign In</a>
        {% endif %}
    </div>
    <div>
        <a href="{% url 'Tech:list' %}">List</a>
    </div>
    {% block content %}
    {% endblock %}
    {% endblock %}
    {% block extra_body %}
    {% endblock %}
  </body>
</html>